name: Markdown lint
on: [push, pull_request]

jobs:
  linting:
    name: "Markdown linting"
    runs-on: ubuntu-20.04 # https://github.com/actions/runner-images/issues/6697
    steps:
    - uses: actions/checkout@v2
      name: Check out the code
    - name: Lint Code Base
      uses: docker://avtodev/markdown-lint:v1
      with:
        args: '**/*.md'
