name: Pull POEditor translations
on: workflow_dispatch

jobs:
  createPullRequest:
    runs-on: ubuntu-20.04 # https://github.com/actions/runner-images/issues/6697
    steps:
      - uses: actions/checkout@v2

      - name: Get Timestamp
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y-%H%M%S')"

      - name: Pull translations
        run: |
          chmod +x ./.github/pull-translations.sh
          ./.github/pull-translations.sh \
          ${{ secrets.POEDITOR_PROJECT_ID }} \
          ${{ secrets.POEDITOR_API_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore: updated localizations"
          branch: "chore/update-localization-${{ steps.date.outputs.date }}"
          delete-branch: true
          title: "chore(bot): updated localizations"
          body: |
            Automatically updated localizations from [POEditor][1]

            [1]: https://poeditor.com/projects/
          draft: false
